# Generated by Django 3.1.7 on 2021-04-13 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210413_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contact_email',
        ),
    ]
