# Generated by Django 3.1.7 on 2021-04-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contact_email',
            field=models.EmailField(default='filleremail@filler.com', max_length=254),
            preserve_default=False,
        ),
    ]
