# Generated by Django 3.1.7 on 2021-04-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210414_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contact_email',
        ),
    ]
