# Generated by Django 3.1.7 on 2021-04-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
