# Generated by Django 3.1.7 on 2021-04-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210414_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='address_other',
            new_name='additional_address_info',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='address_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='address_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='address_state_province',
            new_name='state_or_province',
        ),
    ]
